### ISSUE TITLE
docker-openseamap-renderer uses to much memory, until killed by the kernel

### ISSUE THREAD

**Issue by IeP4nieF** [KastB/docker-openseamap-renderer#1]
After running `[update_maps.sh](https://github.com/KastB/docker-openseamap-renderer/blob/master/update_maps.sh)` all memory is used until the OS kills the process. This starts when it comes to compiling overpass:

    g++ -DHAVE_CONFIG_H -I. -I../../src/test-bin -I..    -std=c++11 -Wall -O2 -MT ../overpass_api/data/way_geometry_store.o -MD -MP -MF $depbase.Tpo -c -o ../overpass_api/data/way_geometry_store.o ../../src/test-bin/../overpass_api/data/way_geometry_store.cc

This happens on Debian bookworm and bullseye.

**Comment by KastB** [comment]
I checked it for me, fixed some dependencies, but the memory issue is probably due to your hardware setup.
Probably you simply have close to no memory available as this is still during installation, not during rendering.
How much is "all memory"?

**Comment by IeP4nieF** [comment]
Thank you for your fast replay. I don't think that this is a hardware issue. Both machines (bookworm and bullseye) have 32GB Ram.

Right after running `update_maps.sh` all memory is "eaten" and the machine starts swaping. Today I managed it after about 8h of swaping to get an ssh shell and do a `killall cc1plus`. This helps immediatly because there where dozens of `cc1plus` processes using to much memory.

So all in all I'm sure it is not a hardware-setup problem. Before running `update_maps.sh` only 10GB of ram were used.

**Comment by KastB** [comment]
True, thats strange. It shouldn't use more than 8GB.
In the update_maps.sh, there are two lines to build docker images.
Could you check which one causes the issues for you?

**Comment by IeP4nieF** [comment]
Not so easy to check, because the machine will start swaping...

But here is my `update_maps.sh`. Because I'm only interested in openseamap I comment out everything else:
```
~/docker-openseamap-renderer$ cat update_maps.sh | grep -v ^#
echo "expecting a new ${data_dir}/data.osm.bz2"
data_dir="/home/fr/openseamap"
level_start=2
level_end=5
latStart=54.78
lonStart=9.39
latEnde=54.93
lonEnde=9.68

name_osm="OpenSeaMapOfflineLakeConstance"
name_seamap="OpenSeaMapOfflineLakeConstance"

docker build -t seamap_renderer -f DockerfileSeamapRenderer .

mkdir -p ${data_dir}/seamap_tiles/
docker run -v ${data_dir}:/data seamap_renderer
echo """
{
        \"bounds\": [
        ${lonStart},
        ${latEnde},
        ${lonEnde},
        ${latStart}
        ],
        \"minzoom\": ${level_start},
        \"maxzoom\": ${level_end},
        \"name\": \"${name_seamap}\",
        \"description\": \"${name_seamap}\",
        \"format\": \"png\"
    }

""" > ${data_dir}/seamap_tiles/metadata.json

docker run -p 8008:80 -v /data/:/data -e DATA="${data_dir}/data.osm.bz osm_renderer &

cd ${data_dir}/seamap_tiles
python -m SimpleHTTPServer 2> /dev/zero > /dev/zero &
docker run -v ${data_dir}/:/opt/app/data -e "APP_MODE=command" -e "TILESERVER_TYPE=osm" -e "TILESERVER_ENDPOINT=http://172.17.0.1:8000/{z}/{x}/{y}.png" -e "APP_TIMEOUT=3000" -e "APP_MINZOOM=9" -e "APP_MAXZOOM=18" -e "APP_MAXAREA=160000" mapsquare/mbtiles-generator-server /opt/app/app.sh --left=8.86 --bottom=47.42 --top=47.82 --right=9.8
```
Probably this line causes the trouble:
    docker build -t seamap_renderer -f DockerfileSeamapRenderer .
But I'm not sure, because there are more `docker run` lines in `update_maps.sh`.

**Comment by KastB** [comment]
Can you execute
`docker build -t seamap_renderer -f DockerfileSeamapRenderer .`
and after that
`docker build -t osm_renderer -f DockerfileOSMRenderer .`

**Comment by IeP4nieF** [comment]
Runing `docker build -t seamap_renderer -f DockerfileSeamapRenderer .` the machine starts to use all the memory again. This is at the moment where dozens of `cc1plus` are started. This time I did a `killall cc1plus` in time.

**Comment by KastB** [comment]
There seems to be only one place where a multithreaded compilation happens.
Maybe you have too many cores (in relation to memory). I limited it to 4 threads, maybe this helps?

**Comment by IeP4nieF** [comment]
I don't think that this was a problem with to many cores, because on one of the two machines where this happens I have only 4C/4T. (On the other 8C/16T.)

Nevertheless now not so many RAM is used. (Only very few!). During the first compilation four threads are used, during the second only one. So it's slow but working. Perhaps it's possible to change to 16 threads? (Or find out why so many threads where used before.)

But there is another problem in `update_map.sh` now:

    docker: Error response from daemon: create ./data/: "./data/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

Using a absolute path in `update_map.sh` solves this.

Running `update_map.sh` leads to the next problem. Should I open a new ticket? I get

    Received error from server{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"172.17.0.1","port":8000}

in a loop from `node`. The only chance was a `kill -s 9 <pid>` as root. Is there something I can check for this problem?

**Comment by IeP4nieF** [comment]
Memory-problem fixed.
