### ISSUE TITLE
./update_maps.sh: line 143: wait: `': not a pid or valid job spec

### ISSUE THREAD

**Issue by cmewse** [KastB/docker-openseamap-renderer#11]
Running update-maps.sh

Waiting for seamap_renderer container to finish...
Waiting for seamap_renderer container to finish...
Waiting for seamap_renderer container to finish...
seamap_renderer container has finished.
Waiting for wait OSM download  to finish
./update_maps.sh: line 143: wait: `': not a pid or valid job spec
Error response from daemon: No such container: seamap_renderer
osm_renderer
generating tiles is completed
generating mbtiles
MBTiles file created successfully at /root/docker-openseamap-renderer/data/osm.mbtiles
MBTiles file created successfully at /root/docker-openseamap-renderer/data/seamap.mbtiles
ALL DONE!

seamap container is removed

OSM container fails to start: Log:
    * Starting PostgreSQL 15 database server
      ...done.
   + sudo -u postgres createuser renderer
   createuser: error: creation of new role failed: ERROR:  role "renderer" already exists

**Comment by KastB** [comment]
Hi,
this message doesn't seem to do any harm.
I updated the scripts so that a "hotstart" is possible now for the seamap renderer as well.
For OSM this was done before. My guess is, that you did not remove the "data_dir" folder => did a hotstat => the user already existed.
