### ISSUE TITLE
How to serve Seamap?

### ISSUE THREAD

**Issue by cmewse** [KastB/docker-openseamap-renderer#13]
So I now have osm and seamap data from your tool (Thanks!) I can serve the osm data with the osm docker server, but how do I display the seamap layer / data?

Or can the data from both be merged into a single mbtiles file?

**Comment by cmewse** [comment]
I could not find a working server that would combine / layer the two maps. I did get tileserver-gl working and a leaflet example to render both as a single map. (Sadly my client front end is a software program which only accepts a single URL)

**Comment by KastB** [comment]
There are several programs to do this.
You can use MBTiles Viewer to load both mbtiles - the overlay works out of the box there.
Or you can mount the squashfs and use that folder in opencpn as a map source.
