### ISSUE TITLE
Connection refused (node) while generating mbtiles

### ISSUE THREAD

**Issue by IeP4nieF** [KastB/docker-openseamap-renderer#2]
Hi,

I tried to generate mbtiles. For this I changed line 63 in `update_maps.sh` from

    exit 0

to

    #exit 0

When it comes to the last step I get

    Received error from server{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"172.17.0.1","port":8008}

Is there something I can try to debug?

And btw: It looks like the corners are hard coded in line 69: `--left=8.86`. Shouldn't it be `--left=${lonstart}` or something like this?

**Comment by IeP4nieF** [comment]
Ok, this was a python3 problem. Changing line 68 in `update_maps.sh` from

    python -m SimpleHTTPServer 2> /dev/zero > /dev/zero &
    
in

    python3 -m http.server 2> /dev/zero > /dev/zero &
    
solves the connection problem.

I would suggest to give a hint in `update_maps.sh` for python3 users.

**Comment by KastB** [comment]
Thank you very much for your feedback. It should be updated in the repo now, as well.
