### ISSUE TITLE
Getting only "Received error from server{"statusCode":404}" while creation of mbtiles

### ISSUE THREAD

**Issue by IeP4nieF** [KastB/docker-openseamap-renderer#3]
After starting the http server (`update_maps.sh` line 69) I get `Received error from server{"statusCode":404}` only from 

    docker run -v ${data_dir}/:/opt/app/data -e "APP_MODE=command" -e "TILESERVER_TYPE=osm" -e "TILESERVER_ENDPOINT=http://172.17.0.1:8000/{z}/{x}/{y}.png" -e "APP_TIMEOUT=3000" -e "APP_MINZOOM=10" -e "APP_MAXZOOM=12" -e "APP_MAXAREA=160000" mapsquare/mbtiles-generator-server /opt/app/app.sh --left=9.45 --bottom=54.8 --top=54.9 --right=9.6

(I set `--left=` and so on to the right values from `latStart=` and so on from `update_maps.sh` and also set MINZOOM and MAXZOOM.)

In deed the docker container tries to get non existing tiles. For example:

    172.17.0.2 - - [15/Mar/2024 15:26:39] "GET /12/2156/1299.png HTTP/1.1" 404 

But

    $ ls 12/2156/
    1297.png  1298.png
    $

Is there anything I can do to help debugging this problem?

**Comment by KastB** [comment]
Hi,
there might be three potential issues here, which you could check/validate
1) Are those tiles at the edge of your area? => There might be rounding errors, which result in the tile renderer to generate fewer tiles than the mbtile-generator requests
2) Are those empty tiles? The seamap is an overlay and empty tiles might not be generated (only water / on land, and therefore no overlay) 
3) Is there a bug, that even if there is no tile, we should answer with an empty png? Does the mbtile-generator retry the requests?

**Comment by IeP4nieF** [comment]
Please excuse my late answer.

This issue is still present.

> * Are those tiles at the edge of your area? => There might be rounding errors, which result in the tile renderer to generate fewer tiles than the mbtile-generator requests

To clarify: Every request of mbtile-generator leads to a 404! There is not a single 200. The mbtile-generator is launched with:

```
$ docker run \
  -v '/home/<user>/docker-openseamap-renderer/data/:/opt/app/data' \
  -e "APP_MODE=command" \
  -e "TILESERVER_TYPE=osm" \
  -e "TILESERVER_ENDPOINT=http://172.17.0.1:8000/{z}/{x}/{y}.png" \
  -e "APP_TIMEOUT=3000" \
  -e "APP_MINZOOM=9" \
  -e "APP_MAXZOOM=18" \
  -e "APP_MAXAREA=160000" \
  ghcr.io/kastb/docker-openseamap-renderer \
  /opt/app/app.sh --left=9.67566 --bottom=47.53688 --top=47.54926 --right=9.69717
```
So it's for sure no rounding problem.

> * Are those empty tiles? The seamap is an overlay and empty tiles might not be generated (only water / on land, and therefore no overlay)

Because every request is a 404, it's definitely not a problem of empty tiles. For example for the bbox
```
latStart=47.54926
lonStart=9.67566
latEnde=47.53688
lonEnde=9.69717
```
there are 4411 tiles in the tiles-dir:

    $ find seamap_tiles/ -name "*png" | wc -l
    4411

> * Is there a bug, that even if there is no tile, we should answer with an empty png? Does the mbtile-generator retry the requests?

The mbtile-generator retries over and over again and won't stop. For the bbox mentioned above the mbtile-generator tries to get 96 uniq tiles. (I installed nginx to serve the tiles and get some logs for debugging.)

**Comment by KastB** [comment]
I refactored the script so that there shouldn't be timing issues anymore, and changed how the mbtiles are generated.
Hopefully this solves this issue

**Comment by KastB** [comment]
I hope this is resolved with the latest updates

**Comment by IeP4nieF** [comment]
Yes! The issue is solved. Thank you very much and please excuse my late answer again.

One hint at the end: Please write in the the readme, that one has to check out the repository for every run of `update_maps.sh`. If you ran `update_maps.sh?` and change the values of  `latStart` and so on after the run, then `update_maps.sh` wont fetch the new data according to the new `latStart` and so on. So either a new checkout of the repository is necessary or one has to delete `data.osm.bz2` manually.
