### ISSUE TITLE
** (process:126): CRITICAL **: 09:09:56.074: No map config sections were found in file: /usr/local/etc/renderd.conf

### ISSUE THREAD

**Issue by cmewse** [KastB/docker-openseamap-renderer#5]
OSM tile server container fails to run

** (process:126): CRITICAL **: 09:09:56.074: No map config sections were found in file: /usr/local/etc/renderd.conf

Steps:
./update_maps.sh
docker run -p 8008:80 -v /OSeaMap/docker-openseamap-renderer/data/:/data -e DATA="/data/data.osm.bz2" osm_renderer

https://github.com/KastB/docker-openseamap-renderer/blob/57c036ecf0bdc45b461c6698176ffd2950d2d93e/scripts/init_osm.sh#L23

**Comment by KastB** [comment]
This issues should be resolved now. Please reopen if this is not true for you
