### ISSUE TITLE
Error response from daemon: Head "https://ghcr.io/v2/kastb/docker-openseamap-renderer/manifests/latest": unauthorized

### ISSUE THREAD

**Issue by cmewse** [KastB/docker-openseamap-renderer#6]
Unable to find image 'ghcr.io/kastb/docker-openseamap-renderer:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/kastb/docker-openseamap-renderer/manifests/latest": unauthorized.
See 'docker run --help'.
./mbtiles_osm.sh: line 30: /opt/app/app.sh: No such file or directory
stop docker containers? [y/n]

**Comment by KastB** [comment]
Did you login with a PAT?
https://stackoverflow.com/questions/72732582/using-github-packages-without-personal-access-token

**Comment by cmewse** [comment]
Thank you for you help!

```
root@ub22:/var/docker-openseamap-renderer# echo $CR_PAT | docker login ghcr.io -u cmewse --password-stdin
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores

Login Succeeded

root@ub22:/var/docker-openseamap-renderer# docker pull ghcr.io/kastb/docker-openseamap-renderer:latest
**Error response from daemon: denied**
```

Is this a permissions issue with your package access?

**Comment by KastB** [comment]
Yes, sorry. It is private by default. Should be public now.
