### ISSUE TITLE
absolute path for `data_dir` necessary

### ISSUE THREAD

**Issue by IeP4nieF** [KastB/docker-openseamap-renderer#8]
I have to change line 22 of `update_maps.sh`

    data_dir="./data"

to absolute path for `data_dir`. Otherwise I get:

    docker: Error response from daemon: create ./data/data.osm.pbf: "./data/data.osm.pbf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

This is with `Docker version 20.10.24+dfsg1, build 297e128` (Debian bookworm).

**Comment by KastB** [comment]
little bit strange, but it should be fixed now
